### ISSUE TITLE
Error message, please help

### ISSUE THREAD

**Issue by lindabroer** [endrebak/snpflip#6] opened 2015-10-14 12:57 UTC
Dear endrebak,

first of, thank you very much for this script. I have just downloaded it and am working on getting it running, but keep running into an error. Could you please have a look? The error is pasted below:

snpflip --bim-file chr1.bim --fasta-genome ucsc.hg19.fasta --output-prefix snpflip_output
Traceback (most recent call last):
  File "/opt/tools/bin/snpflip", line 39, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
  File "/opt/software/python-2.7.10/lib/python2.7/site-packages/snp_flip/table.py", line 11, in create_snp_table
    reference_genome_data = get_reference_genome_data(bim_table, fa_file)
  File "/opt/software/python-2.7.10/lib/python2.7/site-packages/snp_flip/reference_genome.py", line 25, in get_reference_genome_data
    _get_snps = itemgetter(*list(positions))
TypeError: itemgetter expected 1 arguments, got 0

Thanks in advance,

Linda

**Comment by endrebak** [comment] 2015-10-14 13:04
I will look into this tonight. My guess is that it can't find any valid genome positions in the bim file. Would you mind copy/pasting parts of the bim file or upload it somewhere?

What does `cat -et chr1.bim | head` output?

**Comment by endrebak** [comment] 2015-10-14 13:06
Or that it can't work on a single chromo bim...

**Comment by endrebak** [comment] 2015-10-14 13:10
Also what is the output of `grep chr ucsc.hg19.fasta`?

**Comment by lindabroer** [comment] 2015-10-14 13:13
Thank you very much for your quick reply. I actually tried a complete GWAS first, but got the same error there (some chr0, chr25 variants). As I'm currently only interested in few chromosomes, I decided to try that to see if the wrong chromosomes were the issue. They aren't, were just noted to me that they are there.

Output is below:
cat -et chr1.bim | head
1^Irs11240777^I0^I798959^IA^IG$
1^Irs6681049^I0^I800007^IT^IC$
1^Irs4970383^I0^I838555^IT^IG$
1^Irs4475691^I0^I846808^IT^IC$
1^Irs7537756^I0^I854250^IG^IA$
1^Irs2272756^I0^I882033^IT^IC$
1^Irs17160698^I0^I887162^IC^IT$
1^Irs3748597^I0^I888659^IT^IC$
1^Irs6696281^I0^I903104^IT^IC$
1^Irs28391282^I0^I904165^IA^IG$

**Comment by lindabroer** [comment] 2015-10-14 13:14
And the grep output:
grep chr ucsc.hg19.fasta
>chrM
>chr1
>chr2
>chr3
>chr4
>chr5
>chr6
>chr7
>chr8
>chr9
>chr10
>chr11
>chr12
>chr13
>chr14
>chr15
>chr16
>chr17
>chr18
>chr19
>chr20
>chr21
>chr22
>chrX
>chrY
>chr1_gl000191_random
>chr1_gl000192_random
>chr4_ctg9_hap1
>chr4_gl000193_random
>chr4_gl000194_random
>chr6_apd_hap1
>chr6_cox_hap2
>chr6_dbb_hap3
>chr6_mann_hap4
>chr6_mcf_hap5
>chr6_qbl_hap6
>chr6_ssto_hap7
>chr7_gl000195_random
>chr8_gl000196_random
>chr8_gl000197_random
>chr9_gl000198_random
>chr9_gl000199_random
>chr9_gl000200_random
>chr9_gl000201_random
>chr11_gl000202_random
>chr17_ctg5_hap1
>chr17_gl000203_random
>chr17_gl000204_random
>chr17_gl000205_random
>chr17_gl000206_random
>chr18_gl000207_random
>chr19_gl000208_random
>chr19_gl000209_random
>chr21_gl000210_random
>chrUn_gl000211
>chrUn_gl000212
>chrUn_gl000213
>chrUn_gl000214
>chrUn_gl000215
>chrUn_gl000216
>chrUn_gl000217
>chrUn_gl000218
>chrUn_gl000219
>chrUn_gl000220
>chrUn_gl000221
>chrUn_gl000222
>chrUn_gl000223
>chrUn_gl000224
>chrUn_gl000225
>chrUn_gl000226
>chrUn_gl000227
>chrUn_gl000228
>chrUn_gl000229
>chrUn_gl000230
>chrUn_gl000231
>chrUn_gl000232
>chrUn_gl000233
>chrUn_gl000234
>chrUn_gl000235
>chrUn_gl000236
>chrUn_gl000237
>chrUn_gl000238
>chrUn_gl000239
>chrUn_gl000240
>chrUn_gl000241
>chrUn_gl000242
>chrUn_gl000243
>chrUn_gl000244
>chrUn_gl000245
>chrUn_gl000246
>chrUn_gl000247
>chrUn_gl000248
>chrUn_gl000249

**Comment by endrebak** [comment] 2015-10-14 13:15
Thanks, will get back to you.

**Comment by endrebak** [comment] 2015-10-14 15:27
Should be fixed, please try `$ pip install snpflip==0.0.2`.

Thanks for kindly reporting the bug and feel free to reopen if the issue is not fixed for you.

**Closed by endrebak** 2015-10-14 15:27 UTC

**Comment by lindabroer** [comment] 2015-10-15 07:10
Thanks, will try it out straight away.

Linda
