### ISSUE TITLE
error: no objects to concatenate

### ISSUE THREAD

**Issue by laurenleesc** [endrebak/snpflip#12] opened 2015-12-28 21:56 UTC
Hi Again!

Thanks for your script.  I am using the reference genome here:

ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh37/special_requests/

I am getting the following error below:

----------------------------------------------------------
C:\Python27\Scripts>python snpflip --bim-file=nhs_subjects.bim --fasta-genome=GRCh37-lite.fa
Chromosome 0 in .bim, but not in fasta file.
Traceback (most recent call last):
  File "snpflip", line 42, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
  File "C:\Python27\lib\site-packages\snp_flip\table.py", line 11, in create_snp_table
    reference_genome_data = get_reference_genome_data(bim_table, fa_file)
  File "C:\Python27\lib\site-packages\snp_flip\reference_genome.py", line 41, in get_reference_genome_data
    genome_data = pd.concat(chromosome_data)
  File "C:\Python27\lib\site-packages\pandas\tools\merge.py", line 812, in concat
    copy=copy)
  File "C:\Python27\lib\site-packages\pandas\tools\merge.py", line 845, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
-----------------------------------------------------------

Any advice?  Thanks in advance!

**Comment by endrebak** [comment] 2015-12-29 17:22
I am without a computer for a few days now, but I'll look at it when I get back. 

Could you paste the results of 

`head nhs_subjects.bim` and `cut -f 1 nhs_subjects.bim | sort -u`?

Thanks for reporting, btw.

**Comment by laurenleesc** [comment] 2015-12-29 17:38
Hi,

Thanks for your response.

I do not know python very well at all, just PLINK.  I'm also in a windows
environment....here is my feeble attempt :(  Pretty sure you're assuming I
have more skill than I do :)

------------------------------------------------------------------------------------

C:\Python27\Scripts>python snpflip --head nhs_subjects.bim
Usage:
    snpflip --fasta-genome=FA --bim-file=BIM [--output-prefix=PRE]
    snpflip --help
    snpflip --version

**Comment by endrebak** [comment] 2015-12-29 17:51
Would you be able to send me the bim file you are using (by Dropbox or some other means)? Endrebak85@gmail.com

**Comment by laurenleesc** [comment] 2015-12-29 17:56
Unfortunately I cannot because the data is restricted from the NIH and I
had to go through requests and all that stuff.  I could maybe the bim file
in a text editor and examine for format problems?

**Comment by endrebak** [comment] 2015-12-29 21:21
I would need to analyze the contents of your files to see what goes wrong - since the software works for many people the problem is likely on your end.

Perhaps you could ask whether you are allowed to divulge some of the contents of the bim file? It does not contain confidential info (unlike the fam or bed files).

**Comment by laurenleesc** [comment] 2015-12-30 18:46
Hi Endre,

The NIH committee is out until Jan 4th, so I am wondering if we can put
that one one on hold for a bit.  This other error I'm getting:

C:\Python27\Scripts>python snpflip --bim-file=dbgap_chr3.bim
--fasta-genome=GRCh37-lite.fa
Traceback (most recent call last):
  File "snpflip", line 42, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
  File "C:\Python27\lib\site-packages\snp_flip\table.py", line 11, in
create_snp_table
    reference_genome_data = get_reference_genome_data(bim_table, fa_file)
  File "C:\Python27\lib\site-packages\snp_flip\reference_genome.py", line
31, in get_reference_genome_data
    snp_nucleotides = [snp.upper() for snp in _get_snps(str(nucleotides))]
IndexError: string index out of range

Is one I am also interested in.  I had a whole genome (22 chrs) and that
had the same error.  I split the file by chromosome, and all the
chromosomes work now except for 3.....i cannot see anything with my eye in
the bim file that looks different from the other successful chromosomes.
Any ideas?

Thanks!

Lauren

**Comment by endrebak** [comment] 2015-12-30 19:02
I'll update snpflip to diagnose common problems. Will reply here when I am done.

**Comment by laurenleesc** [comment] 2015-12-30 19:22
thank you! happy new year!

**Comment by endrebak** [comment] 2015-12-30 19:33
It will take at least a week though. 

💥🎉🎊

**Comment by endrebak** [comment] 2016-01-04 21:56
Would you mind updating to the latest snpflip (`pip install snpflip==0.0.5`) and then report the error message you get back to me? Thanks and happy new years!

**Comment by laurenleesc** [comment] 2016-01-05 09:52
Happy New Year!

Here is my error message:

C:\Python27\Scripts>python snpflip --bim-file=dbgap_chr3.bim
--fasta-genome=GRCh37-lite.fa
Traceback (most recent call last):
  File "snpflip", line 46, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
  File "C:\Python27\lib\site-packages\snp_flip\table.py", line 9, in
create_snp_table
    bim_table = read_bim_file(bim_file)
  File "C:\Python27\lib\site-packages\snp_flip\bim_file.py", line 11, in
read_bim_file
    dtype={"chromosome": str})
  File "C:\Python27\lib\site-packages\pandas\io\parsers.py", line 498, in
parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Python27\lib\site-packages\pandas\io\parsers.py", line 275, in
_read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Python27\lib\site-packages\pandas\io\parsers.py", line 590, in
__init__
    self._make_engine(self.engine)
  File "C:\Python27\lib\site-packages\pandas\io\parsers.py", line 731, in
_make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Python27\lib\site-packages\pandas\io\parsers.py", line 1103, in
__init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas\parser.pyx", line 353, in pandas.parser.TextReader.__cinit__
(pandas\parser.c:3246)
  File "pandas\parser.pyx", line 591, in
pandas.parser.TextReader._setup_parser_source (pandas\parser.c:6111)
IOError: File dbgap_chr3.bim does not exist

The file does have a chromosome 3 though, but that IS one that if i exclude
in Plink, along with chromosome 4 and 19, then the file works.....

Thanks

**Comment by endrebak** [comment] 2016-01-05 10:16
The error message above just says that it could not find the file `dbgap_chr3.bim`. You probably just misspelled the name or forgot the full path.

Try again with the correct filename/path :)

**Comment by endrebak** [comment] 2016-01-05 10:17
Ps. you should also be able to run `snpflip` with `snpflip -f fasta.fa -b bim.bim`.

**Comment by laurenleesc** [comment] 2016-01-05 10:39
I'm silly, can't believe I used the wrong file.  I'm running a long command
right now, I should be able to get back to you soon though.

**Comment by laurenleesc** [comment] 2016-01-06 09:57
Good morning!

This looks the same as version 0.0.4

C:\Python27\Scripts>python snpflip -f GRCh37-lite.fa -b
dbGaP_Genotypes_Breast_c3.bim
Chromosome 23 in .bim, but not in fasta file.
Chromosome 26 in .bim, but not in fasta file.
There were 69 'N' nucleotides in chromosome 20.
There were 62 'N' nucleotides in chromosome 21.
There were 198 'N' nucleotides in chromosome 22.
There were 253 'N' nucleotides in chromosome 1.
Traceback (most recent call last):
  File "snpflip", line 46, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
  File "C:\Python27\lib\site-packages\snp_flip\table.py", line 11, in
create_snp_table
    reference_genome_data = get_reference_genome_data(bim_table, fa_file)
  File "C:\Python27\lib\site-packages\snp_flip\reference_genome.py", line
37, in get_reference_genome_data
    snp_nucleotides = [snp.upper() for snp in _get_snps(str(nucleotides))]
IndexError: string index out of range

version check:

C:\Python27\Scripts>python snpflip --version
0.0.5

**Comment by endrebak** [comment] 2016-01-06 10:04
Okay, the script ends before it gets to the debug info I added.

That error happens in the part that reads the reference genome (you gave me the link), so I should be able to reproduce and fix it. I'll look at it tonight.

**Comment by endrebak** [comment] 2016-01-06 21:42
I can't reproduce this, unfortunately.

What happens if you use this fasta: http://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz ?

**Comment by laurenleesc** [comment] 2016-01-07 10:13
Hi,

C:\Python27\Scripts>python snpflip -f human_g1k_v37.fasta -b
dbGaP_Genotypes_Breast_c3.bim
Traceback (most recent call last):
  File "snpflip", line 46, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
  File "C:\Python27\lib\site-packages\snp_flip\table.py", line 11, in
create_snp_table
    reference_genome_data = get_reference_genome_data(bim_table, fa_file)
  File "C:\Python27\lib\site-packages\snp_flip\reference_genome.py", line
17, in get_reference_genome_data
    pyfaidx_genome = Fasta(genome_fasta, as_raw=True, read_ahead=100000)
  File "C:\Python27\lib\site-packages\pyfaidx\__init__.py", line 623, in
__init__
    sequence_always_upper=sequence_always_upper)
  File "C:\Python27\lib\site-packages\pyfaidx\__init__.py", line 270, in
__init__
    raise FastaIndexingError(e)
pyfaidx.FastaIndexingError: Line length of fasta file is not consistent!
Inconsistent line found in >MT at line 51594897

**Comment by endrebak** [comment] 2016-01-07 11:31
This means you have an old version of `pyfaidx`, one of the libraries `snpflip` uses. If you do `pip install -U snpflip`, all dependencies should be updated. This might take some time though, since much of the scientific Python stack might be updated too!

**Comment by mdshw5** [comment] 2016-02-24 19:40
You could also just `pip install --upgrade pyfaidx`...

**Comment by endrebak** [comment] 2016-02-24 20:18
You are absolutely correct. 

Closing this, feel free to reopen if you have further qs :)

**Closed by endrebak** 2016-02-24 20:18 UTC
